export const State = {
  ANDAMAN_AND_NICOBAR: 'Andaman and Nicobar Islands',
  ANDHRA_PRADESH: 'Andhra Pradesh',
  ARUNACHAL_PRADESH: 'Arunachal Pradesh',
  ASSAM: 'Assam',
  BIHAR: 'Bihar',
  CHANDIGARH: 'Chandigarh',
  CHHATTISGARH: 'Chhattisgarh',
  DADRA_AND_NAGAR_HAVELI: 'Dadra and Nagar Haveli',
  DAMAN_AND_DIU: 'Daman and Diu',
  DELHI: 'Delhi',
  GOA: 'Goa',
  GUJARAT: 'Gujarat',
  HARYANA: 'Haryana',
  HIMACHAL_PRADESH: 'Himachal Pradesh',
  JAMMU_AND_KASHMIR: 'Jammu and Kashmir',
  JHARKHAND: 'Jharkhand',
  KARNATAKA: 'Karnataka',
  KERALA: 'Kerala',
  MADHYA_PRADESH: 'Madhya Pradesh',
  MAHARASHTRA: 'Maharashtra',
  MANIPUR: 'Manipur',
  MEGHALAYA: 'Meghalaya',
  MIZORAM: 'Mizoram',
  NAGALAND: 'Nagaland',
  ODISHA: 'Odisha',
  PONDICHERRY: 'Pondicherry',
  PUDUCHERRY: 'Puducherry',
  PUNJAB: 'Punjab',
  RAJASTHAN: 'Rajasthan',
  SIKKIM: 'Sikkim',
  TAMIL_NADU: 'Tamil Nadu',
  TELANGANA: 'Telangana',
  TRIPURA: 'Tripura',
  UTTAR_PRADESH: 'Uttar Pradesh',
  UTTARAKHAND: 'Uttarakhand',
  WEST_BENGAL: 'West Bengal'
} as const;

export type State = typeof State[keyof typeof State];
